spring:
    application:
      name:
        apigateway
    cloud:
      gateway:
        server:
          webflux:
            routes:
              - id: authentication
                uri: http://localhost:8983
                predicates:
                  - Path=/auth/**
              - id: userservice
                uri: http://localhost:8981
                predicates:
                  - Path=/api/**
token:
  signing:
    key: ${SECURITY_JWT_SECRET:53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855}
